<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Aqilatun Nafisah">
<meta name="dcterms.date" content="2025-01-14">

<title>Pengaruh Industri Anime Terhadap Pertumbuhan PDB Jepang Pada Periode 2011-2021</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Pengaruh Industri Anime Terhadap Pertumbuhan PDB Jepang Pada Periode 2011-2021</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Aqilatun Nafisah </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 14, 2025</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="poltekapp.jpg" class="img-fluid figure-img" width="443"></p>
</figure>
</div>
<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> Pendahuluan</h2>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> Latar belakang</h3>
<p>Saat ini Jepang dikenal memiliki kekuatan ekonomi terbesar kedua di Asia dan ketiga di dunia, serta memiliki hubungan diplomatik hampir dengan semua negara berdaulat di dunia. Kuatnya Perekonomian Jepang dipengaruhi oleh berbagai sektor, namun sektor industri yang paling berpengaruh terhadap perekonomian Jepang. Salah satu contoh sektor industri yang mampu mendongkrak roda perekonomian Jepang ialah Industri Anime.</p>
<p>Anime merupakan salah satu pesona Jepang dan budaya populer yang sampai sekarang masih sangat disukai di seluruh dunia. Anime telah menjadi salah satu produk ekspor budaya terbesar Jepang dengan popularitas yang tinggi di seluruh dunia pada beberapa tahun terakhir. Anime juga telah membawa pendapatan yang signifikan melalui penjualan hak cipta, merchandise, dan produk terkait lainnya. Hal ini dikarenakan oleh daya tarik anime yang unik dan beragam, seperti alur cerita yang menarik, karakter yang penuh warna, grafis dan animasi yang khas, serta tema yang dapat memikat perhatian berbagai kalangan. Dalam konteks diplomasi budaya, anime menjadi salah satu bentuk ekspresi budaya Jepang yang penting. Anime dapat menjadi sarana untuk mempromosikan budaya Jepang ke seluruh dunia, memperkenalkan nilai-nilai Jepang, serta membangun citra positif terhadap Jepang sebagai negara yang kaya akan budaya (Toi, 2020).</p>
<p>Selain sebagai bentuk upaya ekspansi ke luar negeri, Industri anime juga membawa banyak dampak baik bagi kegiatan perekonomian di dalam negeri. Banyak perusahaan-perusahaan yang berkembang untuk memproduksi anime. Proses pembuatan anime dapat menciptakan lapangan pekerjaan dalam negeri. Hal tersebut dikarenakan dalam membuat anime membutuhkan animator, desainer animasi, <em>seiyuu</em>&nbsp;(pengisi suara), komposer musik, manajemen produksi, dan masih banyak lagi. Produksi anime juga memberininspirasi bagi industri-industri kreatif yang lain seperti manga, video game, merchandise, serta fashion untuk budaya <em>cosplay</em>.</p>
</section>
<section id="ruang-lingkup" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="ruang-lingkup"><span class="header-section-number">1.2</span> Ruang lingkup</h3>
<p>Dalam penelitian ini penulis mengambil objek penelitian dari Anime Industry Data AJA (The Association of Japanese Animation) dan WDI (World Development Indicators). Ruang lingkup penelitian ini terdapat 2 variabel antara lain nilai Pendapatan Industri Anime Jepang dan nilai Produk Domestik Bruto (PDB) Jepang. Pendapatan Industri Anime adalah total pendapatan dari pendapatan Anime (Animasi) Video, TV, Movie , Animasi <em>Online,</em> Ekspor, dan sebagainya yang terkait dengan industri Anime. Data yang digunakan adalah data yang bersifat time series yaitu dalam periode 2011-2021 dengan satuan yen Jepang (¥).</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.3</span> Rumusan masalah</h3>
<ol type="1">
<li>Apakah Industri Anime memiliki pengaruh terhadap PDB Jepang?</li>
<li>Bagaimana hubungan antara Industri Anime Jepang dengan pertumbuhan PDB Jepang?</li>
</ol>
</section>
<section id="tujuan-dan-manfaat-penelitian" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="tujuan-dan-manfaat-penelitian"><span class="header-section-number">1.4</span> Tujuan dan manfaat penelitian</h3>
<p>Penelitian ini dilakukan bertujuan untuk mengetahui pengaruh Industri Anime sebagai salah satu Budaya Populer Jepang terhadap PDB Jepang, serta mengetahui hubungan antara Industri Anime dengan PDB Jepang.</p>
<p>Manfaat dari adanya penelitian ini ialah memberikan pemahaman yang lebih baik tentang kontribusi industri anime terhadap pertumbuhan ekonomi Jepang kepada peneliti dan pembaca atau masyarakat luas yang tertarik dengan industri anime dan pertumbuhan ekonomi Jepang.</p>
</section>
<section id="package" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="package"><span class="header-section-number">1.5</span> Package</h3>
<p>Packages yang digunakan pada penelitian ini antara lain sebagai berikut:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">2</span> Studi pustaka</h2>
<section id="anime" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="anime"><span class="header-section-number">2.1</span> Anime</h3>
<p><strong>Anime</strong> adalah animasi asal Jepang yang digambar menggunakan tangan seperti menggambar dengan manual di kertas dan teknologi komputer yang dapat mempercepat proses pembuatan anime dan menciptakan efek CG. Kata anime (アニメ) adalah singkatan dari animeeshon （アニメーション）yang berasal dari bahasa Inggris, yaitu animation. Terlepas dari asal usul animenya, semua jenis animasi dianggap anime di Jepang. Namun di luar Jepang, kata anime lebih sering digolongkan secara spesifik sebagai animasi yang dibuat di Jepang (Budianto, 2015: 179).</p>
<p><strong>Industri Anime</strong> merupakan industri kreatif yang berfokus pada produksi dan distribusi konten animasi Jepang (Anime)</p>
</section>
<section id="pertumbuhan-ekonomi-produk-domestik-bruto" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="pertumbuhan-ekonomi-produk-domestik-bruto"><span class="header-section-number">2.2</span> Pertumbuhan Ekonomi &amp; Produk Domestik Bruto</h3>
<p><strong>Pertumbuhan ekonomi</strong> menurut Dr.&nbsp;Joko Untoro (2010:39) merupakan perkembangan kegiatan dalam perekonomian yang menyebabkan barang dan jasa yang diproduksi dalam masyarakat bertambah dan kemakmuran masyarakat meningkat dalam jangka panjang.</p>
<p><strong>Produk Domestik Bruto (PDB)</strong> menurut Imamul Arifin &amp; Gina Hadi W (2009:11) merupakan Indikator yang digunakan untuk mengetahui pertumbuhan ekonomi suatu Negara.</p>
</section>
</section>
<section id="metode-penelitian" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">3</span> Metode penelitian</h2>
<section id="data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> Data</h3>
<p>Berikut data yang digunakan sebagai objek penelitian, yaitu data Pendapatan atau Nilai Penjualan Industri Anime (Animasi Jepang) dan PDB Jepang dalam satuan Yen Jepang (¥) pada periode 2011-2021 :</p>
<table class="table">
<thead>
<tr class="header">
<th>Tahun</th>
<th>PDB (Y)</th>
<th>Pendapatan Industri Anime (X)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2011</td>
<td>510.795.175.493.000</td>
<td>1.337.500.000.000</td>
</tr>
<tr class="even">
<td>2012</td>
<td>517.817.337.272.000</td>
<td>1.339.500.000.000</td>
</tr>
<tr class="odd">
<td>2013</td>
<td>528.200.093.617.000</td>
<td>1.476.900.000.000</td>
</tr>
<tr class="even">
<td>2014</td>
<td>529.764.651.420.000</td>
<td>1.637.100.000.000</td>
</tr>
<tr class="odd">
<td>2015</td>
<td>538.032.300.000.000</td>
<td>1.829.200.000.000</td>
</tr>
<tr class="even">
<td>2016</td>
<td>542.088.131.379.000</td>
<td>1.990.300.000.000</td>
</tr>
<tr class="odd">
<td>2017</td>
<td>551.169.905.966.000</td>
<td>2.142.100.000.000</td>
</tr>
<tr class="even">
<td>2018</td>
<td>554.716.083.665.000</td>
<td>2.180.700.000.000</td>
</tr>
<tr class="odd">
<td>2019</td>
<td>552.485.186.424.000</td>
<td>2.514.500.000.000</td>
</tr>
<tr class="even">
<td>2020</td>
<td>528.846.534.864.000</td>
<td>2.419.900.000.000</td>
</tr>
<tr class="odd">
<td>2021</td>
<td>540.177.005.075.000</td>
<td>2.742.500.000.000</td>
</tr>
</tbody>
</table>
<p>Baca Data</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#import dataset</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"E:/Metopel UAS_2023"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"latihan.xlsx"</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  Tahun           PIA     PDB
  &lt;dbl&gt;         &lt;dbl&gt;   &lt;dbl&gt;
1  2011 1337500000000 5.11e14
2  2012 1339500000000 5.18e14
3  2013 1476900000000 5.28e14
4  2014 1637100000000 5.30e14
5  2015 1829200000000 5.38e14
6  2016 1990300000000 5.42e14</code></pre>
</div>
</div>
<p>PIA pada data diatas adalah singkatan dari Pendapatan Industri Anime.</p>
<p>Penelitian ini menggunakan data Pendapatan Industri Anime Jepang yang bersumber dari Anime Industry Data AJA (The Association of Japanese Animation), situs web resmi AJA yang menyediakan “laporan tentang Industri Anime Jepang” yang diterbitkan oleh AJA setiap tahunnya. Laporan tersebut berisi informasi terbaru tentang industri animasi Jepang dan bisnisnya. Laporan ini hanya tersedia dalam bahasa Jepang, namun AJA menyediakan versi ringkasnya untuk pembaca non-Jepang.</p>
<p>Data lain yang digunakan pada penelitian ini adalah data PDB Jepang (Constant LCU) yang bersumber dari World Development Indicators (WDI). WDI merupakan basis data yang dikelola World Bank, sebuah lembaga internasional. WDI memiliki lebih dari 1000 indikator penting dari sekitar 200 negara dengan rentang waktu yang bervariasi.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"ggplot2"</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"readxl"</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"dplyr"</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>dat,<span class="fu">aes</span>(<span class="at">x=</span>PIA,<span class="at">y=</span>PDB))<span class="sc">+</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color=</span><span class="st">"blue"</span>,<span class="at">size=</span><span class="dv">2</span>)<span class="sc">+</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>     <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"tabel 1. Hubungan antara Pendapatan Industri Anime dan PDB Jepang"</span>,</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>          <span class="at">x=</span><span class="st">"Pendapatan Industri Anime"</span>,</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>          <span class="at">y=</span><span class="st">"PDB Jepang"</span>)<span class="sc">+</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>     <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"E:/Metopel UAS_2023"</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"latihan.xlsx"</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(dat)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(PDB<span class="sc">~</span>PIA,<span class="at">data =</span> dat)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>u<span class="ot">&lt;-</span><span class="fu">resid</span>(reg1)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>PIA,dat<span class="sc">$</span>u,<span class="at">xlab =</span> <span class="st">"Pendapatan Industri Anime"</span>,<span class="at">ylab =</span> <span class="st">"error"</span>)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Plot pengaruh error terhadap Pendapatan Industri Anime</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"latihan.xlsx"</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(dat)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(PDB<span class="sc">~</span>PIA,<span class="at">data =</span> dat)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>u<span class="ot">&lt;-</span><span class="fu">resid</span>(reg1)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>PDB,dat<span class="sc">$</span>u,<span class="at">xlab =</span> <span class="st">"PDB Jepang"</span>,<span class="at">ylab =</span> <span class="st">"error"</span>)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Plot pengaruh error terhadap PDB Jepang</p>
</section>
<section id="metode-analisis" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">3.2</span> Metode analisis</h3>
<p>Metode yang dipilih adalah regresi univariat atau Ordinary Least Square (OLS) dengan 1 variabel independen. Penelitian ini bermaksud mencari hubungan antara Pendapatan Industri Anime (X) dengan PDB Jepang (Y). Spesifikasi yang dilakukan adalah:</p>
<p><span class="math display">\[
y_{t}=\beta_0 + \beta_1 x_t+\mu_t
\]</span> di mana <span class="math inline">\(y_t\)</span> adalah PDB Jepang dan <span class="math inline">\(x_t\)</span> adalah Pendapatan Industri Anime .</p>
</section>
</section>
<section id="pembahasan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="pembahasan"><span class="header-section-number">4</span> Pembahasan</h2>
<section id="pembahasan-masalah" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="pembahasan-masalah"><span class="header-section-number">4.1</span> Pembahasan masalah</h3>
<table class="table">
<thead>
<tr class="header">
<th>Variable</th>
<th>Coefficient</th>
<th>Std.Error</th>
<th>t-value</th>
<th>Prob (.)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>4.950e+14</td>
<td>1.400e+13</td>
<td>35.348</td>
<td>5.74e-11</td>
</tr>
<tr class="even">
<td>PIA (x)</td>
<td>2.080e+01</td>
<td>6.939e+00</td>
<td>2.998</td>
<td>0.015</td>
</tr>
<tr class="odd">
<td>R Squared</td>
<td>0.4996</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Adjusted R-Squared</td>
<td>0.444</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>F-Statisctic</td>
<td>8.985</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Prob (F-Statistic)</td>
<td>0.01502</td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>Hasil regresi yang telah didapat dimasukan ke dalam rumus persamaan yang ada sehingga menjadi:</p>
<p><span class="math display">\[
Y=4.950 +2.080X
\]</span></p>
<p>Industri Anime (Animasi Jepang) Berpengaruh positif terhadap peningkatan pertumbuhan ekonomi pada PDB Jepang dikarenakan variabel X yang positif. Jika diasumsikan setiap kenaikan Pendapatan Industri Anime 1, maka PDB Jepang akan meningkat sebesar 2.080. Namun, jika Pendapatan Industri Anime = 0, PDB Jepang akan menurun sebesar 4.950.</p>
<p>Nilai Adjusted R-Squared 0.444 menunjukkan bahwa sebesar 44.4% variabel dependen dapat dijelaskan oleh model regresi. Nilai F-Statistic yang tinggi yaitu sebesar 8.985 dan nilai p-value yang rendah yaitu sebesar 0.01502 menunjukkan bahwa model secara keseluruhan memiliki kecenderungan untuk signifikan. Hal ini berarti bahwa Industri Anime berpengaruh secara signifikan terhadap PDB Jepang.</p>
</section>
<section id="analisis-masalah" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">4.2</span> Analisis masalah</h3>
<p>Hasil regresinya adalah</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(PDB<span class="sc">~</span>PIA,<span class="at">data=</span>dat)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = PDB ~ PIA, data = dat)

Residuals:
       Min         1Q     Median         3Q        Max 
-1.645e+13 -8.419e+12  2.517e+12  5.473e+12  1.439e+13 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 4.950e+14  1.400e+13  35.348 5.74e-11 ***
PIA         2.080e+01  6.939e+00   2.998    0.015 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.062e+13 on 9 degrees of freedom
Multiple R-squared:  0.4996,    Adjusted R-squared:  0.444 
F-statistic: 8.985 on 1 and 9 DF,  p-value: 0.01502</code></pre>
</div>
</div>
<p>Setiap kenaikan Pendapatan Industri Anime dengan diasumsikan nilainya 1, maka dapat meningkatkan PDB Jepang sebesar 2.080. Namun, jika Pendapatan Industri Anime = 0, PDB Jepang dapat menurun sebesar 4.950.</p>
</section>
</section>
<section id="kesimpulan" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">5</span> Kesimpulan</h2>
<p>Berdasarkan pada hasil penelitian ini dapat disimpulkan bahwa Industri Anime memiliki pengaruh yang positif terhadap PDB Jepang. Hal ini dapat terlihat dari hasil analisis regresi yang menunjukkan bahwa setiap kenaikan Pendapatan Industri Anime sebesar 1, maka akan berdampak pada peningkatan PDB Jepang sebesar 2.080. Karena produktivitas dalam Industri Anime di Jepang yang tinggi, maka arus modal yang masuk ke dalam negeri juga meningkat. Namun, jika produktivitas dalam Industri Anime menurun sehingga nilai Pendapatan Industri Anime mencapai nol, maka akan berpengaruh negatif terhadap PDB Jepang yaitu penurunan sebesar 4.950.</p>
<p>Industri Anime bukanlah satu-satunya faktor yang sepenuhnya mempengaruhi PDB Jepang, yang berarti PDB Jepang juga dipengaruhi oleh faktor lain. Meskipun begitu, hasil regresi menunjukkan bahwa Industri Anime memberikan pengaruh yang signifikan terhadap PDB Jepang.</p>
</section>
<section id="referensi" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="referensi"><span class="header-section-number">6</span> Referensi</h2>
<p>Fathurohman, M. J. (2020). Japanese Cultural Diplomacy through Anime Diplomasi Budaya Jepang melalui Anime.</p>
<p>Anime Industry Report 2022 Summary. (n.d.). 日本動画協会. Retrieved January 21, 2024, from <a href="https://aja.gr.jp/download/2022_anime_ind_rpt_summary_en" class="uri">https://aja.gr.jp/download/2022_anime_ind_rpt_summary_en</a></p>
<p><em>World Development Indicators | DataBank</em>. (n.d.). Retrieved January 20, 2024, from <a href="https://databank.worldbank.org/reports.aspx?source=2&amp;series=NY.GDP.MKTP.KD&amp;country=JPN#" class="uri">https://databank.worldbank.org/reports.aspx?source=2&amp;series=NY.GDP.MKTP.KD&amp;country=JPN#</a></p>
<p>Kompasiana.com. (2024, January 2). <em>Peran Penting Industri Kreatif Anime terhadap Perekonomian Jepang</em>. KOMPASIANA. <a href="https://www.kompasiana.com/rahayuad20/659386a5c57afb5e6b2aacb2/peran-penting-industri-kreatif-anime-terhadap-perekonomian-jepang" class="uri">https://www.kompasiana.com/rahayuad20/659386a5c57afb5e6b2aacb2/peran-penting-industri-kreatif-anime-terhadap-perekonomian-jepang</a></p>
<p><em>DIPLOMASI BUDAYA JEPANG DI INDONESIA MELALUI FILM-FILM ANIME STUDIO GHIBLI SEBAGAI UPAYA NATION BRANDING ASPEK KEBUDAYAAN - repo unpas</em>. (n.d.). Retrieved January 22, 2024, from <a href="http://repository.unpas.ac.id/66795/" class="uri">http://repository.unpas.ac.id/66795/</a></p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>